version: "3.3"

services:
  backend:
    build: .
    container_name: blog_backend
    command: python ./src/manage.py runserver 0:8000
    restart: always
    volumes:
    - ./:/srv/project
    ports:
    - "8000:8000"
